definitions:
  carousel.Carousel:
    properties:
      createAt:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      slug:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  carousel.CarouselInput:
    properties:
      isActive:
        type: boolean
      slug:
        type: string
      url:
        type: string
    type: object
  category.Category:
    properties:
      categoryId:
        description: FK
        type: string
      createAt:
        type: string
      id:
        type: string
      name:
        type: string
      slug:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  category.CategoryInput:
    properties:
      name:
        type: string
      slug:
        type: string
      url:
        type: string
    type: object
  product.Product:
    properties:
      categoryId:
        description: FK
        type: string
      createAt:
        type: string
      description:
        type: string
      discount:
        type: number
      id:
        type: string
      isPopular:
        type: boolean
      orderCount:
        type: integer
      price:
        type: number
      tag:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      url:
        items:
          type: string
        type: array
    type: object
  product.ProductInput:
    properties:
      description:
        type: string
      discount:
        type: number
      isPopular:
        type: boolean
      price:
        type: number
      tag:
        type: string
      url:
        items:
          type: string
        type: array
    type: object
  seasonalOffer.SeasonalOffer:
    properties:
      UpdatedAt:
        type: string
      createAt:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      position:
        type: integer
      slug:
        type: string
      url:
        type: string
    type: object
  seasonalOffer.SeasonalOfferInput:
    properties:
      isActive:
        type: boolean
      position:
        type: integer
      slug:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: fahim@example.com
  description: REST API with Go, MongoDB, and Swagger
  title: Initial Project API
  version: "1.0"
paths:
  /carousels:
    get:
      description: Retrieve all carousel items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/carousel.Carousel'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all carousels
      tags:
      - carousels
    post:
      consumes:
      - application/json
      description: Add a new carousel item
      parameters:
      - description: Carousel object
        in: body
        name: carousel
        required: true
        schema:
          $ref: '#/definitions/carousel.CarouselInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/carousel.Carousel'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new carousel
      tags:
      - carousels
  /carousels/{id}:
    delete:
      description: Delete a carousel item
      parameters:
      - description: Carousel ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete carousel by ID
      tags:
      - carousels
    put:
      consumes:
      - application/json
      description: Update an existing carousel
      parameters:
      - description: Carousel ID
        in: path
        name: id
        required: true
        type: string
      - description: Carousel object
        in: body
        name: carousel
        required: true
        schema:
          $ref: '#/definitions/carousel.Carousel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update carousel by ID
      tags:
      - carousels
  /categorys:
    get:
      description: Retrieve all category items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/category.Category'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all categorys
      tags:
      - categorys
    post:
      consumes:
      - application/json
      description: Add a new category item
      parameters:
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/category.CategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/category.Category'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new category
      tags:
      - categorys
  /categorys/{id}:
    delete:
      description: Delete a category item
      parameters:
      - description: category ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete category by ID
      tags:
      - categorys
    put:
      consumes:
      - application/json
      description: Update an existing category
      parameters:
      - description: category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/category.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update category by ID
      tags:
      - categorys
  /health:
    get:
      description: API health status
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health check
      tags:
      - Health
  /products:
    get:
      description: Retrieve all product items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Add a new product item
      parameters:
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.ProductInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/product.Product'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new product
      tags:
      - products
  /products/{id}:
    delete:
      description: Delete a product item
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update an existing product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update product by ID
      tags:
      - products
  /seasonalOffers:
    get:
      description: Retrieve all seasonalOffer items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/seasonalOffer.SeasonalOffer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all seasonalOffers
      tags:
      - seasonalOffers
    post:
      consumes:
      - application/json
      description: Add a new seasonalOffer item
      parameters:
      - description: SeasonalOfferInput object
        in: body
        name: seasonalOffer
        required: true
        schema:
          $ref: '#/definitions/seasonalOffer.SeasonalOfferInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/seasonalOffer.SeasonalOffer'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new seasonalOffer
      tags:
      - seasonalOffers
  /seasonalOffers/{id}:
    delete:
      description: Delete a seasonalOffer item
      parameters:
      - description: SeasonalOffer ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete seasonalOffer by ID
      tags:
      - seasonalOffers
    put:
      consumes:
      - application/json
      description: Update an existing seasonalOffer
      parameters:
      - description: SeasonalOffer ID
        in: path
        name: id
        required: true
        type: string
      - description: SeasonalOffer object
        in: body
        name: seasonalOffer
        required: true
        schema:
          $ref: '#/definitions/seasonalOffer.SeasonalOffer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update seasonalOffer by ID
      tags:
      - seasonalOffers
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload an image/file and return public URL
      parameters:
      - description: Upload file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload a file
      tags:
      - upload
swagger: "2.0"
